In [1]:
import tensorflow as tf
import numpy as np
N = 500
a, b, h, alpha = 0, 1, np.sqrt(2), 1

training_data = np.linspace(a, b, N, endpoint=False)[1:]
x = tf.convert_to_tensor(training_data)
x_t = tf.reshape(x, shape=(1,len(training_data)))
xtrans = tf.transpose(x)
print(x_t)
print(xtrans)
x



tf.Tensor(
[[0.002 0.004 0.006 0.008 0.01  0.012 0.014 0.016 0.018 0.02  0.022 0.024
  0.026 0.028 0.03  0.032 0.034 0.036 0.038 0.04  0.042 0.044 0.046 0.048
  0.05  0.052 0.054 0.056 0.058 0.06  0.062 0.064 0.066 0.068 0.07  0.072
  0.074 0.076 0.078 0.08  0.082 0.084 0.086 0.088 0.09  0.092 0.094 0.096
  0.098 0.1   0.102 0.104 0.106 0.108 0.11  0.112 0.114 0.116 0.118 0.12
  0.122 0.124 0.126 0.128 0.13  0.132 0.134 0.136 0.138 0.14  0.142 0.144
  0.146 0.148 0.15  0.152 0.154 0.156 0.158 0.16  0.162 0.164 0.166 0.168
  0.17  0.172 0.174 0.176 0.178 0.18  0.182 0.184 0.186 0.188 0.19  0.192
  0.194 0.196 0.198 0.2   0.202 0.204 0.206 0.208 0.21  0.212 0.214 0.216
  0.218 0.22  0.222 0.224 0.226 0.228 0.23  0.232 0.234 0.236 0.238 0.24
  0.242 0.244 0.246 0.248 0.25  0.252 0.254 0.256 0.258 0.26  0.262 0.264
  0.266 0.268 0.27  0.272 0.274 0.276 0.278 0.28  0.282 0.284 0.286 0.288
  0.29  0.292 0.294 0.296 0.298 0.3   0.302 0.304 0.306 0.308 0.31  0.312
  0.314 0.316 0.318 0.32  0.3

<tf.Tensor: shape=(499,), dtype=float64, numpy=
array([0.002, 0.004, 0.006, 0.008, 0.01 , 0.012, 0.014, 0.016, 0.018,
       0.02 , 0.022, 0.024, 0.026, 0.028, 0.03 , 0.032, 0.034, 0.036,
       0.038, 0.04 , 0.042, 0.044, 0.046, 0.048, 0.05 , 0.052, 0.054,
       0.056, 0.058, 0.06 , 0.062, 0.064, 0.066, 0.068, 0.07 , 0.072,
       0.074, 0.076, 0.078, 0.08 , 0.082, 0.084, 0.086, 0.088, 0.09 ,
       0.092, 0.094, 0.096, 0.098, 0.1  , 0.102, 0.104, 0.106, 0.108,
       0.11 , 0.112, 0.114, 0.116, 0.118, 0.12 , 0.122, 0.124, 0.126,
       0.128, 0.13 , 0.132, 0.134, 0.136, 0.138, 0.14 , 0.142, 0.144,
       0.146, 0.148, 0.15 , 0.152, 0.154, 0.156, 0.158, 0.16 , 0.162,
       0.164, 0.166, 0.168, 0.17 , 0.172, 0.174, 0.176, 0.178, 0.18 ,
       0.182, 0.184, 0.186, 0.188, 0.19 , 0.192, 0.194, 0.196, 0.198,
       0.2  , 0.202, 0.204, 0.206, 0.208, 0.21 , 0.212, 0.214, 0.216,
       0.218, 0.22 , 0.222, 0.224, 0.226, 0.228, 0.23 , 0.232, 0.234,
       0.236, 0.238, 0.24 , 0.242, 0.244, 

In [6]:
"""
Builds a customized neural network model.
"""
architectures = [16]
initializer = "GlorotNormal"
activation = "sigmoid"

hidden_layers_len = len(architectures)
input_tensor = tf.keras.layers.Input(shape=(1,))
zeroes = tf.zeros(shape=(N,1))
hidden_layers = []

if hidden_layers_len >= 1:
    hidden_layer = tf.keras.layers.Dense(architectures[0], kernel_initializer=initializer,
                                         bias_initializer='zeros', activation=activation)(input_tensor)
    hidden_layers.append(hidden_layer)
    for architecture in zip(architectures[1:]):
        hidden_layer = tf.keras.layers.Dense(architecture, kernel_initializer=initializer,
                                             bias_initializer='zeros', activation=activation)(zeroes)
        hidden_layers.append(hidden_layer)

    output_layer = tf.keras.layers.Dense(1, kernel_initializer=initializer, bias_initializer='zeros',
                                         activation=tf.identity)(hidden_layers[-1])
else:
    output_layer = tf.keras.layers.Dense(1, kernel_initializer=initializer, bias_initializer='zeros',
                                         activation=tf.identity)(input_tensor)

model = tf.keras.Model(inputs=input_tensor, outputs=output_layer)
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense_4 (Dense)             (None, 16)                32        
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 49
Trainable params: 49
Non-trainable params: 0
_________________________________________________________________
